void back();
void ground();
void cylinder(float radius, float height, int sides);
void stair(float width, float height, float depth);
void cuboid(float width, float height, float depth);
void cone(float r, float h1, float h2, float thetah, float theta1, float theta2);
void frustum(float radius1, float radius2, float height, int sides);
void branch();
void hill();
void tori(int x, int y, int z, int i);
void lake(float radius, int x, int y, float ovalx, float ovaly);
void initTexture();
